@startuml
'https://plantuml.com/sequence-diagram


abstract class AbstractList

User -> DB: Authentication Request
DB --> User: Authentication Response

AbstractList <|-- Query
DB <|== AbstractList

class Query {
    Object [] elementData
    size()

}


@enduml