# Form implementation generated from reading ui file 'C:\Users\sibregion\Pictures\window3.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi (self, MainWindow3):
        MainWindow3.setObjectName("MainWindow3")
        MainWindow3.resize(600, 366)
        MainWindow3.setMaximumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon.fromTheme("C:\\Users\\sibregion\\Desktop\\icons8-автомобиль-26.png")
        MainWindow3.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow3)
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(-1, 9, -1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent = self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(600, 600))
        self.tabWidget.setTabletTracking(True)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("QTabBar::tab\n"
                                     "{\n"
                                     "background-color:rgba(255, 48, 12,100);\n"
                                     "\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:selected\n"
                                     "{\n"
                                     "background-color:rgb(255,255,255)\n"
                                     "}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit1 = QtWidgets.QPlainTextEdit(parent = self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit1.sizePolicy().hasHeightForWidth())
        self.plainTextEdit1.setSizePolicy(sizePolicy)
        self.plainTextEdit1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.plainTextEdit1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.plainTextEdit1.setBackgroundVisible(False)
        self.plainTextEdit1.setCenterOnScroll(True)
        self.plainTextEdit1.setObjectName("plainTextEdit1")
        self.verticalLayout_2.addWidget(self.plainTextEdit1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(parent = self.tab_2)
        self.plainTextEdit_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.plainTextEdit_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_3.addWidget(self.plainTextEdit_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(parent = self.tab_3)
        self.plainTextEdit_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(parent = self.tab_4)
        self.plainTextEdit_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.verticalLayout_5.addWidget(self.plainTextEdit_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(parent = self.tab_5)
        self.plainTextEdit_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.plainTextEdit_5.setBackgroundVisible(False)
        self.plainTextEdit_5.setCenterOnScroll(False)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.verticalLayout_4.addWidget(self.plainTextEdit_5)
        self.done_pushButton = QtWidgets.QPushButton(parent = self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done_pushButton.sizePolicy().hasHeightForWidth())
        self.done_pushButton.setSizePolicy(sizePolicy)
        self.done_pushButton.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.done_pushButton.setObjectName("done_pushButton")
        self.verticalLayout_4.addWidget(self.done_pushButton)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow3.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow3)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

    def retranslateUi (self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow3", "Дорога \"Название дороги\""))
        self.plainTextEdit1.setPlaceholderText(_translate("MainWindow3", "Заполните описание"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1),
                                  _translate("MainWindow3", "Краткая историческая справка"))
        self.plainTextEdit_2.setPlaceholderText(_translate("MainWindow3", "Заполните описание"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  _translate("MainWindow3", "Связь дороги с железнодорожными и водными путями"))
        self.plainTextEdit_3.setPlaceholderText(_translate("MainWindow3", "Заполните описание"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3),
                                  _translate("MainWindow3", "Экономическое и административное занчение дороги"))
        self.plainTextEdit_4.setPlaceholderText(_translate("MainWindow3", "Заполните описание"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4),
                                  _translate("MainWindow3", "Характеристика движения"))
        self.plainTextEdit_5.setPlaceholderText(_translate("MainWindow3", "Заполните описание"))
        self.done_pushButton.setText(_translate("MainWindow3", "Готово"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5),
                                  _translate("MainWindow3", "Топографические условия района"))


class Window3(QtWidgets.QMainWindow, Ui_MainWindow3):
    def __init__ (self):
        # Это здесь нужно для доступа к переменным, методам
        # и т.д. в файле design.py
        super().__init__()
        self.setupUi(self)  # Это нужно для инициализации нашего дизайна


def main ():
    app = QtWidgets.QApplication(sys.argv)  # Новый экземпляр QApplication
    window = Window3()  # Создаём объект класса ExampleApp
    window.show()  # Показываем окно
    app.exec()  # и запускаем приложение


if __name__ == '__main__':  # Если мы запускаем файл напрямую, а не импортируем
    main()  # то запускаем функцию main()
