# Form implementation generated from reading ui file 'C:\Users\sibregion\Pictures\window2.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from interface import window3
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi (self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(520, 260)
        MainWindow2.setMinimumSize(QtCore.QSize(520, 260))
        MainWindow2.setMaximumSize(QtCore.QSize(520, 260))
        self.centralwidget = QtWidgets.QWidget(parent = MainWindow2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.client_lineEdit = QtWidgets.QLineEdit(parent = self.centralwidget)
        self.client_lineEdit.setStyleSheet("")
        self.client_lineEdit.setObjectName("client_lineEdit")
        self.horizontalLayout_5.addWidget(self.client_lineEdit)
        self.label_7 = QtWidgets.QLabel(parent = self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.client_boss_lineEdit = QtWidgets.QLineEdit(parent = self.centralwidget)
        self.client_boss_lineEdit.setObjectName("client_boss_lineEdit")
        self.horizontalLayout_5.addWidget(self.client_boss_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent = self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.year_lineEdit = QtWidgets.QLineEdit(parent = self.centralwidget)
        self.year_lineEdit.setStyleSheet("")
        self.year_lineEdit.setObjectName("year_lineEdit")
        self.gridLayout.addWidget(self.year_lineEdit, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent = self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.cypher_lineEdit = QtWidgets.QLineEdit(parent = self.centralwidget)
        self.cypher_lineEdit.setStyleSheet("")
        self.cypher_lineEdit.setObjectName("cypher_lineEdit")
        self.gridLayout.addWidget(self.cypher_lineEdit, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent = self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.contractor_lineEdit = QtWidgets.QLineEdit(parent = self.centralwidget)
        self.contractor_lineEdit.setStyleSheet("")
        self.contractor_lineEdit.setObjectName("contractor_lineEdit")
        self.horizontalLayout_10.addWidget(self.contractor_lineEdit)
        self.label_8 = QtWidgets.QLabel(parent = self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.contractor_boss_lineEdit = QtWidgets.QLineEdit(parent = self.centralwidget)
        self.contractor_boss_lineEdit.setObjectName("contractor_boss_lineEdit")
        self.horizontalLayout_10.addWidget(self.contractor_boss_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent = self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tp_checkBox = QtWidgets.QCheckBox(parent = self.centralwidget)
        self.tp_checkBox.setAutoFillBackground(False)
        self.tp_checkBox.setTristate(False)
        self.tp_checkBox.setObjectName("tp_checkBox")
        self.horizontalLayout.addWidget(self.tp_checkBox)
        self.dad_checkBox = QtWidgets.QCheckBox(parent = self.centralwidget)
        self.dad_checkBox.setObjectName("dad_checkBox")
        self.horizontalLayout.addWidget(self.dad_checkBox)
        self.podd_checkBox = QtWidgets.QCheckBox(parent = self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.podd_checkBox.sizePolicy().hasHeightForWidth())
        self.podd_checkBox.setSizePolicy(sizePolicy)
        self.podd_checkBox.setObjectName("podd_checkBox")
        self.horizontalLayout.addWidget(self.podd_checkBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent = self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.road_city_radioButton = QtWidgets.QRadioButton(parent = self.centralwidget)
        self.road_city_radioButton.setEnabled(False)
        self.road_city_radioButton.setObjectName("road_city_radioButton")
        self.verticalLayout.addWidget(self.road_city_radioButton)
        self.roads_automobile_radioButton = QtWidgets.QRadioButton(parent = self.centralwidget)
        self.roads_automobile_radioButton.setEnabled(False)
        self.roads_automobile_radioButton.setObjectName("roads_automobile_radioButton")
        self.verticalLayout.addWidget(self.roads_automobile_radioButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent = self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.count_region_lineEdit = QtWidgets.QLineEdit(parent = self.centralwidget)
        self.count_region_lineEdit.setStyleSheet("")
        self.count_region_lineEdit.setObjectName("count_region_lineEdit")
        self.horizontalLayout_2.addWidget(self.count_region_lineEdit)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cance_pushButton = QtWidgets.QPushButton(parent = self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cance_pushButton.sizePolicy().hasHeightForWidth())
        self.cance_pushButton.setSizePolicy(sizePolicy)
        self.cance_pushButton.setObjectName("cance_pushButton")
        self.cance_pushButton.clicked.connect(self.close_window)
        self.horizontalLayout_3.addWidget(self.cance_pushButton)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.next_pushButton = QtWidgets.QPushButton(parent = self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_pushButton.sizePolicy().hasHeightForWidth())
        self.next_pushButton.setSizePolicy(sizePolicy)
        self.next_pushButton.setObjectName("next_pushButton")
        self.next_pushButton.clicked.connect(self.window3)

        self.horizontalLayout_3.addWidget(self.next_pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 8, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        MainWindow2.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow2)
        self.tp_checkBox.toggled['bool'].connect(self.roads_automobile_radioButton.setEnabled)  # type: ignore
        self.tp_checkBox.toggled['bool'].connect(self.road_city_radioButton.setEnabled)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)
        MainWindow2.setTabOrder(self.tp_checkBox, self.dad_checkBox)
        MainWindow2.setTabOrder(self.dad_checkBox, self.podd_checkBox)
        MainWindow2.setTabOrder(self.podd_checkBox, self.road_city_radioButton)
        MainWindow2.setTabOrder(self.road_city_radioButton, self.roads_automobile_radioButton)
        MainWindow2.setTabOrder(self.roads_automobile_radioButton, self.count_region_lineEdit)
        MainWindow2.setTabOrder(self.count_region_lineEdit, self.client_lineEdit)
        MainWindow2.setTabOrder(self.client_lineEdit, self.client_boss_lineEdit)
        MainWindow2.setTabOrder(self.client_boss_lineEdit, self.contractor_lineEdit)
        MainWindow2.setTabOrder(self.contractor_lineEdit, self.contractor_boss_lineEdit)
        MainWindow2.setTabOrder(self.contractor_boss_lineEdit, self.cypher_lineEdit)
        MainWindow2.setTabOrder(self.cypher_lineEdit, self.year_lineEdit)
        MainWindow2.setTabOrder(self.year_lineEdit, self.cance_pushButton)
        MainWindow2.setTabOrder(self.cance_pushButton, self.next_pushButton)

    def retranslateUi (self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "\"Название дороги\""))
        self.label_7.setText(_translate("MainWindow2", "Руководитель"))
        self.label_4.setText(_translate("MainWindow2", "Год"))
        self.label_3.setText(_translate("MainWindow2", "Заказчик"))
        self.label_6.setText(_translate("MainWindow2", "Шифр"))
        self.label_8.setText(_translate("MainWindow2", "Руководитель"))
        self.label_5.setText(_translate("MainWindow2", "Подрядчик"))
        self.tp_checkBox.setText(_translate("MainWindow2", "Технический паспорт"))
        self.dad_checkBox.setText(_translate("MainWindow2", "Диагностика"))
        self.podd_checkBox.setText(_translate("MainWindow2", "ПОБДД"))
        self.label.setText(_translate("MainWindow2", "Тип документа"))
        self.road_city_radioButton.setText(_translate("MainWindow2", "Городская дорога"))
        self.roads_automobile_radioButton.setText(_translate("MainWindow2", "Автомобильная дорога"))
        self.label_2.setText(_translate("MainWindow2", "Количество участков"))
        self.cance_pushButton.setText(_translate("MainWindow2", "Отмена"))
        self.next_pushButton.setText(_translate("MainWindow2", "Далее"))


class Window2(QtWidgets.QMainWindow, Ui_MainWindow2):
    def __init__ (self, title = None, parent = None):
        # Это здесь нужно для доступа к переменным, методам
        # и т.д. в файле design.py
        super().__init__()
        self.parent = parent
        self.setupUi(self)  # Это нужно для инициализации нашего дизайна
        self.setWindowTitle(title)

    def window3 (self):
        self.window3 = window3.Window3(self.windowTitle())
        self.window3.show()

    def close_window(self):
        #print("Закрытие окна 2")
        self.parent.window().show()
        self.window().close()

def main ():
    app = QtWidgets.QApplication(sys.argv)  # Новый экземпляр QApplication
    window = Window2()  # Создаём объект класса ExampleApp
    window.show()  # Показываем окно
    sys.exit(app.exec())  # и запускаем приложение


if __name__ == '__main__':  # Если мы запускаем файл напрямую, а не импортируем
    main()  # то запускаем функцию main()
